version: '1'

services:
  db:
      image: mongo
      container_name: db
      restart: unless-stopped
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      ports:
          - "27017:27017"
      volumes:
        - dbdata:/data/db
      networks:
        - app-network
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules: