version: "3.8"

services:
  mysql_server:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - TZ/America/Sao_Paulo

  rpgsys_backend:
    depends_on:
      - mysql_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SECRET=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=172.17.0.1
      - DB_PORT=
      - NODE_ENV=development
    ports:
      - "3333:3333"
    volumes:
      - .:/docker/app