export declare class Sheet {
    id: number;
    playerName: string;
    profileImageUrl: string;
    name: string;
    age: number;
    gender: string;
    nex: number;
    rank: string;
    class: string;
    origin: string;
    effortPoints: number;
    maxEffortPoints: number;
    proficiences: string;
    attributes: string;
    skills: string;
    abilities: string;
    rituals: string;
    weapons: string;
    inventory: string;
    hp: number;
    maxHp: number;
    sanity: number;
    maxSanity: number;
    passiveDefense: number;
    blockDefense: number;
    dodgeDefense: number;
    physicsResistance: number;
    ballisticResistance: number;
    energyResistance: number;
    bloodResistance: number;
    deathResistance: number;
    knowledgeResistance: number;
    insanityResistance: number;
    notes: string;
    updateData(newSheet: any): void;
    parseArrays(): void;
}
